create table sensor
(
    id   integer generated by default as identity
        primary key,
    name varchar(100) not null
        unique
);

alter table sensor
    owner to postgres;

create table measurement
(
    id                    integer generated by default as identity
        primary key,
    value                 double precision not null,
    raining               boolean          not null,
    measurement_date_time timestamp        not null,
    sensor                varchar(100)
        references sensor (name)
);

alter table measurement
    owner to postgres;